/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,u=function(a,b){a=a.split(".");for(var c=k,e;a.length&&(e=a.shift());)a.length||b===void 0?c=c[e]&&c[e]!==Object.prototype[e]?c[e]:c[e]={}:c[e]=b},w=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.B=function(e,d,h){for(var p=Array(arguments.length-2),m=2;m<arguments.length;m++)p[m-2]=arguments[m];return b.prototype[d].apply(e,p)}};function y(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}w(y,Error);y.prototype.name="CustomError";function z(a,b){a=a.split("%s");for(var c="",e=a.length-1,d=0;d<e;d++)c+=a[d]+(d<b.length?b[d]:"%s");y.call(this,c+a[e])}w(z,y);z.prototype.name="AssertionError";var A=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var d=Array.prototype.slice.call(arguments,2)}throw new z(""+e,d||[]);}return a};var B=Array.prototype.forEach?function(a,b){A(a.length!=null);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,e=typeof a==="string"?a.split(""):a,d=0;d<c;d++)d in e&&b.call(void 0,e[d],d,a)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var D={};var E=function(a){if(D!==D)throw Error("Bad secret");this.A=a};E.prototype.toString=function(){return this.A};new E("about:blank");new E("about:invalid#zClosurez");var F=[],aa=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};F.indexOf(aa)===-1&&F.push(aa);var G,H;a:{for(var ba=["CLOSURE_FLAGS"],J=k,K=0;K<ba.length;K++)if(J=J[ba[K]],J==null){H=null;break a}H=J}var ca=H&&H[610401301];G=ca!=null?ca:!1;function da(){var a=k.navigator;return a&&(a=a.userAgent)?a:""}var L,ea=k.navigator;L=ea?ea.userAgentData||null:null;function M(a){if(!G||!L)return!1;for(var b=0;b<L.brands.length;b++){var c=L.brands[b].brand;if(c&&c.indexOf(a)!=-1)return!0}return!1}function N(a){return da().indexOf(a)!=-1};function O(){return G?!!L&&L.brands.length>0:!1};var fa=da().toLowerCase().indexOf("webkit")!=-1&&!N("Edge")&&N("Mobile");var ha=N("Safari")&&!((O()?M("Chromium"):(N("Chrome")||N("CriOS"))&&(O()||!N("Edge"))||N("Silk"))||(O()?0:N("Coast"))||(O()?0:N("Opera"))||(O()?0:N("Edge"))||(O()?M("Microsoft Edge"):N("Edg/"))||(O()?M("Opera"):N("OPR"))||N("Firefox")||N("FxiOS")||N("Silk")||N("Android"))&&!(N("iPhone")&&!N("iPod")&&!N("iPad")||N("iPad")||N("iPod"));var ka=function(a){var b=window;fa&&ha&&b?(b.focus(),ia(b,a,0)):(a.close(),ja(a))},ia=function(a,b,c){a.setTimeout(function(){b.closed||c==5?ja(b):(b.close(),c++,ia(a,b,c))},1E3)},ja=function(a){if(!a.closed&&a.document&&a.document.body)if(a=a.document.body,A(a!=null,"goog.dom.setTextContent expects a non-null value for node"),"textContent"in a)a.textContent="Please close this window.";else if(a.nodeType==3)a.data="Please close this window.";else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=
a.firstChild;)a.removeChild(A(a.lastChild));a.firstChild.data="Please close this window."}else{for(var b;b=a.firstChild;)a.removeChild(b);A(a,"Node cannot be null or undefined.");a.appendChild((a.nodeType==9?a:a.ownerDocument||a.document).createTextNode("Please close this window."))}};var la=function(a){if(!a)return"";if(/^about:(?:blank|srcdoc)$/.test(a))return window.origin||"";a.indexOf("blob:")===0&&(a=a.substring(5));a=a.split("#")[0].split("?")[0];a=a.toLowerCase();a.indexOf("//")==0&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");c!=-1&&(b=b.substring(0,c));c=a.substring(0,a.indexOf("://"));if(!c)throw Error("URI is missing protocol: "+a);if(c!=="http"&&c!=="https"&&c!=="chrome-extension"&&
c!=="moz-extension"&&c!=="file"&&c!=="android-app"&&c!=="chrome-search"&&c!=="chrome-untrusted"&&c!=="chrome"&&c!=="app"&&c!=="devtools")throw Error("Invalid URI scheme in origin: "+c);a="";var e=b.indexOf(":");if(e!=-1){var d=b.substring(e+1);b=b.substring(0,e);if(c==="http"&&d!=="80"||c==="https"&&d!=="443")a=":"+d}return c+"://"+b+a};function ma(){function a(){d[0]=1732584193;d[1]=4023233417;d[2]=2562383102;d[3]=271733878;d[4]=3285377520;v=q=0}function b(g){for(var l=p,f=0;f<64;f+=4)l[f/4]=g[f]<<24|g[f+1]<<16|g[f+2]<<8|g[f+3];for(f=16;f<80;f++)g=l[f-3]^l[f-8]^l[f-14]^l[f-16],l[f]=(g<<1|g>>>31)&4294967295;g=d[0];var n=d[1],r=d[2],t=d[3],R=d[4];for(f=0;f<80;f++){if(f<40)if(f<20){var x=t^n&(r^t);var I=1518500249}else x=n^r^t,I=1859775393;else f<60?(x=n&r|t&(n|r),I=2400959708):(x=n^r^t,I=3395469782);x=((g<<5|g>>>27)&4294967295)+x+
R+I+l[f]&4294967295;R=t;t=r;r=(n<<30|n>>>2)&4294967295;n=g;g=x}d[0]=d[0]+g&4294967295;d[1]=d[1]+n&4294967295;d[2]=d[2]+r&4294967295;d[3]=d[3]+t&4294967295;d[4]=d[4]+R&4294967295}function c(g,l){if(typeof g==="string"){g=unescape(encodeURIComponent(g));for(var f=[],n=0,r=g.length;n<r;++n)f.push(g.charCodeAt(n));g=f}l||(l=g.length);f=0;if(q==0)for(;f+64<l;)b(g.slice(f,f+64)),f+=64,v+=64;for(;f<l;)if(h[q++]=g[f++],v++,q==64)for(q=0,b(h);f+64<l;)b(g.slice(f,f+64)),f+=64,v+=64}function e(){var g=[],l=
v*8;q<56?c(m,56-q):c(m,64-(q-56));for(var f=63;f>=56;f--)h[f]=l&255,l>>>=8;b(h);for(f=l=0;f<5;f++)for(var n=24;n>=0;n-=8)g[l++]=d[f]>>n&255;return g}for(var d=[],h=[],p=[],m=[128],C=1;C<64;++C)m[C]=0;var q,v;a();return{reset:a,update:c,digest:e,digestString:function(){for(var g=e(),l="",f=0;f<g.length;f++)l+="0123456789ABCDEF".charAt(Math.floor(g[f]/16))+"0123456789ABCDEF".charAt(g[f]%16);return l}}};var na=function(a,b,c){var e=[];if((Array.isArray(null)?2:1)==1)return e=[b,a],B(c,function(m){e.push(m)}),P(e.join(" "));var d=[],h=[];B(null,function(m){h.push(m.key);d.push(m.value)});var p=Math.floor((new Date).getTime()/1E3);e=d.length==0?[p,b,a]:[d.join(":"),p,b,a];B(c,function(m){e.push(m)});a=P(e.join(" "));p=[p,a];h.length==0||p.push(h.join(""));return p.join("_")},P=function(a){var b=ma();b.update(a);return b.digestString().toLowerCase()};var oa=function(a){var b=a||[];a=[];for(var c=0,e=b.length;c<e;++c){var d=String(b[c]||"");d&&a.push(d)}if(a.length<2)return null;b=a[0];c=gadgets.rpc.getOrigin(a[1]);if(c!==a[1])return null;a=a.slice(2);return(a=(c&&b?["session_state",na(la(c),b,a||[])].join(" "):null)||"")&&a.substr(14)||null},Q=function(a,b,c){this.o=String(a||"");this.j=String(b||"");this.h=String(c||"");this.g={};this.u=this.v=this.l=this.m="";this.i=null};
Q.prototype.evaluate=function(){var a={},b="";try{b=String(document.cookie||"")}catch(p){}b=b.split("; ").join(";").split(";");for(var c=0,e=b.length;c<e;++c){var d=b[c],h=d.indexOf("=");h!=-1?a[d.substr(0,h)]=d.substr(h+1):a[d]=null}this.g=a;if(this.g.SAPISID||this.g.APISID||this.g["__Secure-3PAPISID"])if(this.j=this.j.split(".")[0].split("@")[0],this.l=pa(this,this.o))if(a=gadgets.rpc.getOrigin(String(window.location.href)),this.m=pa(this,a)){b=String(this.g.LSOLH||"").split(":");c=b.length;if(c==
1||c==4)this.v=b[0];if(c==3||c==4)a=String(b[c-3]||""),b=String(b[c-1]||""),c=this.m,a?(e=[a],c&&e.push(c),c=P(e.join(" ")).substr(0,4)):c=null,c===b&&(this.u=a);this.h&&(a=this.h.indexOf("."),a!=-1&&(a=this.h.substr(0,a)||"",this.h=a+"."+oa([this.l,this.o,this.j,this.v,this.u,a]).substr(0,4)));a=oa([this.l,this.o,this.j,this.h]);this.h&&(a=a+"."+this.h);this.i=a}else this.i="";else this.i=""};
var pa=function(a,b){(b=String(a.g[b.indexOf("https://")==0?"SAPISID":"APISID"]||""))||(b=String(a.g["__Secure-3PAPISID"]||""));return b};Q.prototype.getVersionInfo=function(a){var b=parseInt(a,10);if(String(b)!=a||!(b>=0))return null;a=this.u;if(!a)return null;a=a.split("|");return a.length<=b?null:a[b]||null};
var qa=function(a,b,c){a=new Q(a,b,c);a.evaluate();return a},S=function(a,b,c){c=c||ra(this);var e=null;if(a){a=String(a);var d=a.indexOf(".");d!=-1&&(e=a.substr(d+1))}b=qa(c,b,e).i;if(a==null||a=="")a=b==a;else if(b==null||b.length!=a.length)a=!1;else{e=c=0;for(d=a.length;e<d;++e)c|=a.charCodeAt(e)^b.charCodeAt(e);a=c==0}return a},T=function(a,b,c){c=c||ra(this);c=qa(c);if(String(a)!=c.i)throw Error("Unauthorized request");return c.getVersionInfo(String(b))},ra=function(a){a=String(a.origin||"");
if(!a)throw Error("RPC has no origin.");return a};u("checkSessionState",S);u("getVersionInfo",T);var U,V,W,X,Y,Z,sa=window,ta=(window.location.href||sa.location.href).match(RegExp(".*(\\?|#|&)usegapi=([^&#]+)"))||[];
"1"===decodeURIComponent(ta[ta.length-1]||"")?(W=function(a,b,c,e,d,h){U.send(b,d,e,h||gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)},X=function(a,b){U.register(a,b,gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)},Y=function(a){var b=/^(?:https?:\/\/)?[0-9.\-A-Za-z]+(?::\d+)?/.exec(a);b=gapi.iframes.makeWhiteListIframesFilter([b?b[0]:null]);W("..","oauth2callback",gadgets.rpc.getAuthToken(".."),void 0,a,b)},V=function(){ua()},Z=function(){W("..","oauth2relayReady",gadgets.rpc.getAuthToken(".."));X("check_session_state",
va);X("get_versioninfo",wa)}):(W=function(a,b,c,e,d){gadgets.rpc.call(a,b+":"+c,e,d)},X=function(a,b){gadgets.rpc.register(a,b)},Y=function(a){gadgets.rpc.getTargetOrigin("..")==gadgets.rpc.getOrigin(a)&&W("..","oauth2callback",gadgets.rpc.getAuthToken(".."),void 0,a)},V=function(){Z()},Z=function(){W("..","oauth2relayReady",gadgets.rpc.getAuthToken(".."));X("check_session_state",S);X("get_versioninfo",T)});
var ua=function(){var a=Z;window.gapi.load("gapi.iframes",function(){U=gapi.iframes.getContext().getParentIframe();a()})},xa=function(a){window.setTimeout(function(){Y(a)},1)},va=function(a){if(a){var b=a.session_state;var c=a.client_id}return S(b,c,U.getOrigin())},wa=function(a){return T(a.xapisidHash,a.sessionIndex,U.getOrigin())},ya=!1,za=!1,Aa=function(){za=!0;ya&&V()};u("oauth2callback",xa);
u("oauth2verify",function(a,b){var c=window.open("about:blank",a),e;if(c&&!c.closed&&(e=c.oauth2callbackUrl))return window.timeoutMap=window.timeoutMap||{},window.realSetTimeout=window.realSetTimeout||window.setTimeout,window.setTimeout=function(d,h){try{var p=d,m=!1;d=function(){if(!m){m=!0;try{window.timeoutMap[String(q)]=void 0,delete window.timeoutMap[String(q)]}catch(v){}return p.call(this)}};var C=c.setTimeout(d,h);var q=window.realSetTimeout(d,h);window.timeoutMap[String(q)]=C;return q}catch(v){}return window.realSetTimeout(d,
h)},window.realClearTimeout=window.realClearTimeout||window.clearTimeout,window.clearTimeout=function(d){try{var h=window.timeoutMap[String(d)];h&&c.clearTimeout(h)}catch(p){}try{window.timeoutMap[String(d)]=void 0,delete window.timeoutMap[String(d)]}catch(p){}window.realClearTimeout(d)},xa(String(e)),"keep_open"!=b&&ka(c),!0;c&&!c.closed&&ka(c);return!1});u("init",function(){ya=!0;za&&V()});window.addEventListener?window.addEventListener("load",Aa,!1):window.attachEvent("onload",Aa);
