(function(){'use strict';/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g=this||self;function l(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=g,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function p(a,b){a=a.split(".");for(var c=g,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};function q(a){g.setTimeout(()=>{throw a;},0)};var r=l(748402147,l(1,!1));let t=void 0;function x(a,b=!1){return b&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol()}var y=x(),z=x(),A=x("m_m",!0);const C=x("jas",!0);var D={};function E(a,b){return b===void 0?a.i!==F&&!!(2&(a.g[C]|0)):!!(2&b)&&a.i!==F}const F={};var aa=Object.freeze({});var G=typeof g.BigInt==="function"&&typeof g.BigInt(0)==="bigint";const ba=Number.MIN_SAFE_INTEGER.toString(),ca=G?BigInt(Number.MIN_SAFE_INTEGER):void 0,da=Number.MAX_SAFE_INTEGER.toString(),ea=G?BigInt(Number.MAX_SAFE_INTEGER):void 0;function H(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(let c=0;c<a.length;c++){const d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};function fa(a){return a};function I(a,b,c,d){var e=d!==void 0;d=!!d;const h=[];var f=a.length;let k,m=4294967295,P=!1;const B=!!(b&64),u=B?b&128?0:-1:void 0;if(!(b&1||(k=f&&a[f-1],k!=null&&typeof k==="object"&&k.constructor===Object?(f--,m=f):k=void 0,!B||b&128||e))){P=!0;var n;m=((n=ha)!=null?n:fa)(m-u,u,a,k,void 0)+u}b=void 0;for(e=0;e<f;e++)if(n=a[e],n!=null&&(n=c(n,d))!=null)if(B&&e>=m){const v=e-u;let w;((w=b)!=null?w:b={})[v]=n}else h[e]=n;if(k)for(let v in k){a=k[v];if(a==null||(a=c(a,d))==null)continue;f=+v;let w;
if(B&&!Number.isNaN(f)&&(w=f+u)<m)h[w]=a;else{let Q;((Q=b)!=null?Q:b={})[v]=a}}b&&(P?h.push(b):h[m]=b);return h}function J(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(G?a>=ca&&a<=ea:a[0]==="-"?H(a,ba):H(a,da))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){const b=a[C]|0;return a.length===0&&b&1?void 0:I(a,b,J)}if(a!=null&&a[A]===D)return K(a);return}return a}let ha;function K(a){a=a.g;return I(a,a[C]|0,J)};function ia(a){if(a==null){var b=32;a=[]}else{if(!Array.isArray(a))throw Error("narr");b=a[C]|0;if(r&&1&b)throw Error("rfarr");2048&b&&!(2&b)&&ja();if(b&256)throw Error("farr");if(b&64)return b&2048||(a[C]=b|2048),a;var c=a;b|=64;var d=c.length;if(d){var e=d-1;d=c[e];if(d!=null&&typeof d==="object"&&d.constructor===Object){const h=b&128?0:-1;e-=h;if(e>=1024)throw Error("pvtlmt");for(const f in d){const k=+f;if(k<e)c[k+h]=d[f],delete d[f];else break}b=b&-8380417|(e&1023)<<13}}}a[C]=b|2112;return a}
function ja(){if(r)throw Error("carr");if(z!=null){var a;var b=(a=t)!=null?a:t={};a=b[z]||0;a>=5||(b[z]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",q(b))}};function ka(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=L(a,c,!1,b&&!(c&16)):(a[C]|=34,c&4&&Object.freeze(a)));return a}if(a!=null&&a[A]===D)return b=a.g,c=b[C]|0,E(a,c)?a:M(a,b,c)?N(a,b):L(b,c)}function N(a,b,c){a=new a.constructor(b);c&&(a.i=F);a.l=F;return a}function L(a,b,c,d){d!=null||(d=!!(34&b));a=I(a,b,ka,d);d=32;c&&(d|=2);b=b&8380609|d;a[C]=b;return a}
function M(a,b,c){return c&2?!0:c&32&&!(c&4096)?(b[C]=c|2,a.i=F,!0):!1};function O(a,b,c){if(a.i===F){var d=a.g;d=L(d,d[C]|0);d[C]|=2048;a.g=d;a.i=void 0;a.l=void 0;d=!0}else d=!1;if(!d&&E(a,a.g[C]|0))throw Error();a=a.g;d=a[C]|0;if(c===-1)var e=null;else{e=c+-1;var h=a.length-1;if(h<0)e=void 0;else if(e>=h){var f=a[h];f!=null&&typeof f==="object"&&f.constructor===Object?e=f[c]:e===h?e=f:e=void 0}else e=a[e]}h=void 0===aa;var k=!h;f=d;e!=null&&e[A]===D?b=e:Array.isArray(e)?(k=e[C]|0,f=k|f&32|f&2,f!==k&&(e[C]=f),b=new b(e)):k?f&2?((f=b[y])||(k=new b,f=k.g,f[C]|=34,f=b[y]=
k),b=f):b=new b:b=void 0;if(!h||b){h=b.g;f=h[C]|0;b=E(b,f)?M(b,h,f)?N(b,h,!0):new b.constructor(L(h,f,!1)):b;if(e!==b){a:{e=b;h=c+-1;f=a.length-1;if(f>=0&&h>=f&&(k=a[f],k!=null&&typeof k==="object"&&k.constructor===Object)){k[c]=e;break a}if(h<=f)a[h]=e;else if(e!==void 0){let m;f=((m=d)!=null?m:d=a[C]|0)>>13&1023||536870912;c>=f?e!=null&&(a[f+-1]={[c]:e}):a[h]=e}}c=d;c===void 0&&(c=a[C]|0);c&32&&!(c&4096)&&(a[C]=c|4096)}return b}};var R=class{constructor(a){this.g=ia(a)}toJSON(){var a=K(this);return a}};R.prototype[A]=D;R.prototype.toString=function(){return this.g.toString()};function S(a){return b=>{if(b==null||b=="")b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("dnarr");b[C]|=32;b=new a(b)}return b}};var la=class extends R{};var ma=class extends R{};var na=class extends R{};var oa=S(class extends R{});function T(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function U(a,b){a.body.dispatchEvent(new CustomEvent(b,{detail:void 0}))}
var pa=class{constructor(a){this.body=a;this.g=[];T(a,"sampling_mod");var b=T(a,"namespace");if(!b){b=Math.random;b="ns-"+b().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if(c[d].getAttribute("name")==="namespace"&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}if(!(this.g.length>0)){a=T(this.body,"environment");for(const d of a.split("|"))d&&this.g.push(d)}}};var qa=S(class extends R{});function V(a){if(a.i.offsetWidth<=1||a.i.offsetHeight<=1)return!1;a.g.remove();U(a.l,"spanReady");return!0}
var ra=class{constructor(a){this.l=a;this.config={v:!1,u:100};this.i=document.createElement("span");this.g=document.createElement("div");this.i.style.fontSize="6px";this.i.textContent="go";this.g.style.position="absolute";this.g.style.top="100%";this.g.style.left="100%";this.g.style.width="1px";this.g.style.height="0";this.g.style.overflow="hidden";this.g.style.visibility="hidden";this.g.appendChild(this.i)}wait(){if(!this.config.v&&(U(this.l,"spanStart"),this.l.body.appendChild(this.g),!V(this)))return new Promise(a=>
{const b=setInterval(()=>{V(this)&&(clearInterval(b),a())},this.config.u)})}};var sa=class{constructor(a){this.config=a;this.g=O(a,ma,1);O(a,na,12);O(this.g,la,10)}};function ta(a){a.l.length=0;a.i=!0}function W(a,b){a.g=!0;const c=()=>{a.i=!1;const d=a.l.shift();return d===void 0?(a.g=!1,Promise.resolve()):W(a,d())};return b?b.then(c,()=>{if(a.i)return c();a.g=!1;return Promise.reject()}):c()}function ua(a,b){for(const c of b)a.l.push(c);if(!a.g)return W(a)}var va=class{constructor(){this.i=this.g=!1;this.l=[]}};function wa(a){ta(a.l);return ua(a.l,[()=>{if(!a.m){var b=T(a.i.body,"render_config")||"[]";b=qa(b);b=new sa(b);a.m=b}b=(new ra(a.i)).wait();U(a.i,"browserStart");U(a.i,"browserStartEnd");a.g&=-31;a.g|=2;return b},()=>{U(a.i,"browserReady");U(a.i,"browserReadyEnd");a.g|=4;U(a.i,"overallReady")},()=>{U(a.i,"browserQuiet");U(a.i,"browserQuietEnd");a.g|=8}])}function X(a){oa(T(a.i.body,"engine_msg")||"[]");return wa(a)||Promise.resolve()}
var Y=class{constructor(a,b){this.l=new va;this.g=0;this.i=new pa(b)}o(){return this.g}init(){this.g&=-31;this.g|=1;let a=0;const b=this.i.body;b.addEventListener("browserRender",()=>{++a;if(a===1)U(this.i,"overallStart"),X(this).then(()=>{U(this.i,"overallQuiet")});else{var c=b.clientHeight;b.clientWidth&&c&&X(this)}})}};let Z;p("mys.engine.init",(a,b)=>{Z=new Y(a,b);Z.init()});p("mys.engine.stage",()=>{let a;return((a=Z)==null?void 0:a.g)||0});p("mys.Engine",Y);p("mys.Engine.prototype.i",Y.prototype.init);p("mys.Engine.prototype.s",Y.prototype.o);}).call(this);
